networks:
  default:
    driver: bridge
services:
  application_service:
    build:
      context: .
      dockerfile: bun.bookworm-slim.dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "1G"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: always
    image: application_image
    container_name: application_container