export const laptopRepairPrice = [
    {
        model: "15s-eq3053ci",
        series: '',
        vendor: "hp",
        display: 15.6,
        processor: 2.0,
        processorVendor: 'AMD',
        processorName: 'Ryzen 7 5825U (8 cores) 2 - 4,5 ГГц',
        video: 'AMD Radeon 7 Graphics',
        ram: 16,
        ramType: 'DDR4',
        processorReleaseDate: '04.01.2022',
        price: {},
        examples: [],
    },
    {
        model: "14-dv0090ur",
        series: 'Pavilion',
        vendor: "hp",
        display: 14,
        processor: 2.0,
        processorVendor: 'Intel',
        processorName: 'Core i3-1125G4 (4 cores) 2 - 3,7 ГГц',
        video: 'Intel UHD Graphics (G4)',
        ram: 8,
        ramType: 'DDR4',
        processorReleaseDate: '01.09.2020',
        price: {},
        examples: [],
    },
    {
        model: "A317-54-54T2",
        series: 'Aspire 3',
        vendor: "acer",
        display: 17.3,
        processor: 1.3,
        processorVendor: 'Intel',
        processorName: 'Core i5-1235U (10 cores) 1,3 - 4,4 ГГц',
        video: 'Intel Iris Xe Graphics 80',
        ram: 8,
        ramType: 'DDR4',
        processorReleaseDate: '23.02.2022',
        price: {},
        examples: [],
    },
]